### ISSUE TITLE
while the video is buffering from the internet due to slow internet it causes the error

### ISSUE THREAD

**Issue by anilpandey071999** [Athanax/video_player_controls#1]
![Screenshot (117)](https://user-images.githubusercontent.com/31802461/93708957-25514b80-fb58-11ea-9794-24ed854ba63c.png)

══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter ( 4034): The following NoSuchMethodError was thrown while dispatching notifications for
I/flutter ( 4034): VideoPlayerController:
I/flutter ( 4034): The getter 'inSeconds' was called on null.
I/flutter ( 4034): Receiver: null
I/flutter ( 4034): Tried calling: inSeconds
I/flutter ( 4034): 
I/flutter ( 4034): When the exception was thrown, this was the stack:
I/flutter ( 4034): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
I/flutter ( 4034): #1      _VideoPlayerInterfaceState.listenables (package:video_player_controls/video_player_controls.dart:572:47)
I/flutter ( 4034): #2      _VideoPlayerInterfaceState.listener (package:video_player_controls/video_player_controls.dart:566:7)
I/flutter ( 4034): #3      _VideoPlayerInterfaceState.initializeVideo.<anonymous closure> (package:video_player_controls/video_player_controls.dart:170:29)
I/flutter ( 4034): #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:207:21)
I/flutter ( 4034): #5      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:274:5)
I/flutter ( 4034): #6      VideoPlayerController.setLooping (package:video_player/video_player.dart:364:5)
I/flutter ( 4034): #7      _VideoPlayerInterfaceState.initializeVideo (package:video_player_controls/video_player_controls.dart:179:34)
I/flutter ( 4034): #8      _VideoPlayerInterfaceState.startPlayer (package:video_player_controls/video_player_controls.dart:148:5)
I/flutter ( 4034): #9      _VideoPlayerInterfaceState.build.<anonymous closure> (package:video_player_controls/video_player_controls.dart:304:21)
I/flutter ( 4034): #10     _BlocListenerBaseState._subscribe.<anonymous closure> (package:flutter_bloc/src/bloc_listener.dart:187:26)
I/flutter ( 4034): (elided 17 frames from dart:async)
I/flutter ( 4034): 
I/flutter ( 4034): The VideoPlayerController sending notification was:
I/flutter ( 4034):   VideoPlayerController#8f5e6(VideoPlayerValue(duration: null, size: null, position: 0:00:00.000000,
I/flutter ( 4034):   caption: Instance of 'Caption', buffered: [], isPlaying: false, isLooping: false, isBuffering:
I/flutter ( 4034):   falsevolume: 1.0, errorDescription: null))
I/flutter ( 4034): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/ExoPlayerImpl( 4034): Release ab0d166 [ExoPlayerLib/2.9.6] [generic_x86, sdk_google_atv_x86, unknown, 28] [goog.exo.core]
D/SurfaceUtils( 4034): disconnecting from surface 0xcba93808, reason disconnectFromSurface
I/ExoPlayerImpl( 4034): Init 689df2 [ExoPlayerLib/2.9.6] [generic_x86, sdk_google_atv_x86, unknown, 28]
I/OMXClient( 4034): IOmx service obtained
D/SurfaceUtils( 4034): connecting to surface 0xc348d808, reason connectToSurface
I/MediaCodec( 4034): [OMX.google.h264.decoder] setting surface generation to 4130853
D/SurfaceUtils( 4034): disconnecting from surface 0xc348d808, reason connectToSurface(reconnect)
D/SurfaceUtils( 4034): connecting to surface 0xc348d808, reason connectToSurface(reconnect)
E/ACodec  ( 4034): [OMX.google.h264.decoder] setPortMode on output to DynamicANWBuffer failed w/ err -1010
I/ACodec  ( 4034): codec does not support config priority (err -1010)
I/OMXClient( 4034): IOmx service obtained
I/ACodec  ( 4034): codec does not support config priority (err -2147483648)
D/MediaCodec( 4034): [OMX.google.h264.decoder] setting dataspace on output surface to #104
W/MapperHal( 4034): buffer descriptor with invalid usage bits 0x2000
D/SoftwareRenderer( 4034): setting dataspace on output surface to #104

════════ Exception caught by foundation library ════════════════════════════════════════════════════
The following NoSuchMethodError was thrown while dispatching notifications for VideoPlayerController:
The setter 'position=' was called on null.
Receiver: null
Tried calling: position=Instance of 'Duration'

When the exception was thrown, this was the stack: 
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
#1      _VideoPlayerInterfaceState.listenables.<anonymous closure> (package:video_player_controls/video_player_controls.dart:582:19)
#2      State.setState (package:flutter/src/widgets/framework.dart:1233:30)
#3      _VideoPlayerInterfaceState.listenables (package:video_player_controls/video_player_controls.dart:581:5)
#4      _VideoPlayerInterfaceState.listener (package:video_player_controls/video_player_controls.dart:566:7)
...
The VideoPlayerController sending notification was: VideoPlayerController#8f5e6(VideoPlayerValue(duration: 0:00:37.011000, size: Size(1280.0, 720.0), position: 0:00:00.000000, caption: Instance of 'Caption', buffered: [], isPlaying: false, isLooping: false, isBuffering: falsevolume: 1.0, errorDescription: null))
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by foundation library ════════════════════════════════════════════════════
The setter 'position=' was called on null.
Receiver: null
Tried calling: position=Instance of 'Duration'
════════════════════════════════════════════════════════════════════════════════════════════════════
W/MapperHal( 4034): buffer descriptor with invalid usage bits 0x2000
W/MapperHal( 4034): buffer descriptor with invalid usage bits 0x2000
D/HostConnection( 4034): HostConnection::get() New Host Connection established 0xc4154230, tid 20024
D/HostConnection( 4034): HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_dma_v1 ANDROID_EMU_async_unmap_buffer GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_2

**Comment by Athanax** [comment]
Am sorry this happened, am currently solving the issue. Am doing a mass upgrade to the package. Am working on some support plugins to make the package better. I'll make sure I close the issue when done.

**Comment by Athanax** [comment]
I have corrected in version 2.1.7.
The package also has added functionality. I've documented the changes I've made well.
I've also changed the TV UI to make it as per the TV app recommendations, Ease of use.
![Screenshot_1602484958](https://user-images.githubusercontent.com/40561409/95722609-d42b0800-0c7c-11eb-92a7-e0a4c7acfa41.png)
